// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/data/projects.ts
var projects = [
  // ── SOLUTIONS (5) ──
  {
    slug: "ai-chatbot",
    title: "AI Chatbot",
    client: "Internal / Multi-client",
    year: 2026,
    category: "AI Agent",
    filterTag: "Solutions",
    thumbnailType: "image",
    thumbnail: "/images/ai-chatbot.webp",
    summary: "Conversational AI agents for client engagement",
    intro: "Businesses needed always-on client communication without scaling headcount. We built a conversational AI system that handles intake, qualification, and routing.",
    metadata: { year: 2026, duration: "3 Weeks", client: "Multi-client", category: "AI Agent" },
    challenges: {
      heading: "Most chatbot solutions felt robotic and generic, failing to capture brand voice or handle nuanced queries.",
      body: "Off-the-shelf chatbots created frustrating user experiences. Clients needed something that understood context, maintained personality, and escalated intelligently."
    },
    solutions: {
      heading: "We engineered a custom conversational agent with brand-specific training, context memory, and smart handoff to human operators.",
      body: "The system adapts tone to match each client's brand, remembers conversation history within sessions, and routes complex queries to the right team member. Deployment takes under a week."
    },
    gallery: [
      "/images/ai-chatbot.webp"
    ],
    externalLink: "https://chat-sage-gamma.vercel.app/"
  },
  {
    slug: "director-gpt",
    title: "DirectorGPT",
    client: "Internal",
    year: 2026,
    category: "AI Tool",
    filterTag: "Solutions",
    thumbnailType: "image",
    thumbnail: "/images/directorgpt-thumb.jpg",
    summary: "AI-powered film direction and scene planning assistant",
    intro: "DirectorGPT helps filmmakers pre-visualize scenes, generate shot lists, and plan productions with AI assistance.",
    metadata: { year: 2026, duration: "4 Weeks", client: "Internal", category: "AI Tool" },
    challenges: {
      heading: "Pre-production planning is time-consuming and requires expensive pre-visualization tools.",
      body: "Independent filmmakers and small studios lack access to professional pre-viz software, making it hard to communicate creative vision."
    },
    solutions: {
      heading: "We built an AI director assistant that generates shot lists, storyboards, and scene breakdowns from natural language descriptions.",
      body: "DirectorGPT understands film grammar, camera angles, and lighting setups \u2014 turning text descriptions into actionable production plans."
    },
    gallery: [
      "/images/directorgpt-thumb.jpg"
    ],
    externalLink: "https://directorgpt-720109186790.us-west1.run.app/"
  },
  {
    slug: "resume-match",
    title: "ResuMatch AI",
    client: "Intl Campus Admit",
    year: 2026,
    category: "AI Tool",
    filterTag: "Solutions",
    thumbnailType: "image",
    thumbnail: "/images/resume-match.webp",
    summary: "AI-powered resume screening and candidate matching",
    intro: "Admissions and HR teams were drowning in applications with no efficient way to surface the best-fit candidates.",
    metadata: { year: 2026, duration: "5 Weeks", client: "Intl Campus Admit", category: "AI Tool" },
    challenges: {
      heading: "Manual resume review was slow, inconsistent, and unable to scale with application volume.",
      body: "Reviewers spent hours on each batch. Qualified candidates were missed. Bias crept in from fatigue."
    },
    solutions: {
      heading: "We developed an AI matching engine that scores candidates against role requirements, surfacing top matches instantly.",
      body: "The system parses resumes, extracts structured data, and ranks candidates on configurable criteria. Review time dropped by over 80%."
    },
    gallery: [
      "/images/resume-match.webp"
    ],
    externalLink: "https://resumatch-ai-720109186790.us-west1.run.app/"
  },
  {
    slug: "work-schedule",
    title: "WorkBack",
    client: "Internal",
    year: 2026,
    category: "Productivity Tool",
    filterTag: "Solutions",
    thumbnailType: "image",
    thumbnail: "/images/work-schedule.webp",
    summary: "Intelligent scheduling and workflow optimization",
    intro: "Managing overlapping productions, contractor availability, and delivery deadlines across time zones needed a smarter system.",
    metadata: { year: 2026, duration: "4 Weeks", client: "Internal", category: "Productivity Tool" },
    challenges: {
      heading: "Spreadsheet-based scheduling created conflicts, missed deadlines, and zero visibility into team capacity.",
      body: "With contractors across multiple time zones and overlapping project timelines, manual coordination was breaking down."
    },
    solutions: {
      heading: "We built an automated scheduler that factors in availability, dependencies, and deadlines \u2014 with real-time conflict detection.",
      body: "The tool syncs with team calendars, flags bottlenecks before they happen, and provides a visual timeline of all active productions."
    },
    gallery: [
      "/images/work-schedule.webp"
    ],
    externalLink: "https://workback-720109186790.us-west1.run.app/"
  },
  {
    slug: "campus-convert",
    title: "Campus Convert",
    client: "Intl Campus Admit",
    year: 2026,
    category: "AI Tool",
    filterTag: "Solutions",
    thumbnailType: "image",
    thumbnail: "/images/campus-convert-thumb.jpg",
    summary: "Automated GPA conversion across global education systems",
    intro: "International admissions required converting grades from dozens of country-specific systems into a standardized format.",
    metadata: { year: 2026, duration: "3 Weeks", client: "Intl Campus Admit", category: "AI Tool" },
    challenges: {
      heading: "Each country uses a different grading scale, and manual conversion was error-prone and time-consuming.",
      body: "Admissions staff spent significant time cross-referencing conversion tables. Errors led to incorrect eligibility assessments."
    },
    solutions: {
      heading: "We built an automated converter supporting 50+ global grading systems with instant, accurate results.",
      body: "The tool handles percentage-based, letter-grade, and point-based systems. It provides equivalency explanations and supports batch processing."
    },
    gallery: [
      "/images/campus-education.webp"
    ],
    externalLink: "https://campus-convert-720109186790.us-west1.run.app/"
  },
  // ── BRANDING (4) ──
  {
    slug: "creator-con",
    title: "Creator Con",
    client: "Creator Con",
    year: 2025,
    category: "Logo Design",
    filterTag: "Branding",
    thumbnailType: "image",
    thumbnail: "/images/branding-creative.webp",
    externalLink: "https://www.instagram.com/reel/DNyYORtYvWv/",
    tripleVideoPreview: [
      "/videos/creator-con-1.mov",
      "/videos/creator-con-2.m4v",
      "/videos/creator-con-3.mov"
    ],
    summary: "Logo design for a creator economy conference brand",
    intro: "Creator Con needed a visual identity that felt bold, digital-native, and instantly recognizable across social and event signage.",
    metadata: { year: 2025, duration: "2 Weeks", client: "Creator Con", category: "Logo Design" },
    challenges: {
      heading: "The brand had no visual identity \u2014 just a name. It needed to feel premium but accessible, digital but human.",
      body: "The logo would live across screens, signage, merch, and social media \u2014 it had to be versatile and instantly recognizable at any scale."
    },
    solutions: {
      heading: "We developed a bold, geometric wordmark with a dynamic color system that adapts across digital and physical contexts.",
      body: "The identity system includes primary and secondary lockups, a custom color palette, and usage guidelines. It launched across all conference materials."
    },
    gallery: [
      "/images/branding-creative.webp"
    ]
  },
  {
    slug: "vaseline-campaign",
    title: "Vaseline",
    client: "Vaseline",
    year: 2024,
    category: "Creative Campaign",
    filterTag: "Branding",
    thumbnailType: "video",
    thumbnail: "/lovable-uploads/a2bc0601-961e-40cb-80c4-ee53a8664039.png",
    videoPreviewUrl: "/videos/vaseline-preview.mov",
    summary: "Creative marketing campaign with AI-enhanced visual assets",
    intro: "Vaseline needed a fresh campaign that stood out in a saturated personal care market using modern creative techniques.",
    metadata: { year: 2024, duration: "3 Weeks", client: "Vaseline", category: "Creative Campaign" },
    challenges: {
      heading: "The brand wanted to feel contemporary and innovative without alienating its trusted, heritage audience.",
      body: "Balancing tradition with innovation required careful creative direction \u2014 bold enough to turn heads, familiar enough to feel trusted."
    },
    solutions: {
      heading: "We produced an AI-enhanced campaign that blended product photography with generative textures and environments.",
      body: "The campaign assets ran across social, digital display, and print. AI generation accelerated production while maintaining art-directed quality."
    },
    gallery: [
      "/lovable-uploads/a2bc0601-961e-40cb-80c4-ee53a8664039.png"
    ],
    externalLink: "https://readymag.website/surzayon/5140874/"
  },
  {
    slug: "wine-label",
    title: "Wine Label",
    client: "CHCA Wines",
    year: 2024,
    category: "Packaging Design",
    filterTag: "Branding",
    thumbnailType: "video",
    thumbnail: "/lovable-uploads/a2bc0601-961e-40cb-80c4-ee53a8664039.png",
    videoPreviewUrl: "/videos/wine-label-preview.mp4",
    summary: "Label and packaging design for an artisanal wine brand",
    intro: "CHCA Wines needed a label that communicated craft, provenance, and shelf presence in a crowded retail environment.",
    metadata: { year: 2024, duration: "3 Weeks", client: "CHCA Wines", category: "Packaging Design" },
    challenges: {
      heading: "The existing label was forgettable on the shelf, blending into a sea of similar boutique wine branding.",
      body: "The wine itself was exceptional but the packaging told no story. Retailers and consumers weren't picking it up."
    },
    solutions: {
      heading: "We designed a label system with bold typography, textured stock, and a distinctive color palette that commands attention.",
      body: "The final design tells the vineyard story through layered print techniques \u2014 embossing, foil, and custom illustration. Sales increased measurably after relaunch."
    },
    gallery: [],
    externalLink: "https://www.s.pictures/design/chcawinelabel"
  },
  {
    slug: "youtube-pitch-deck",
    title: "Twenty Years of YouTube",
    client: "YouTube (concept)",
    year: 2025,
    category: "Pitch Deck",
    filterTag: "Branding",
    thumbnailType: "image",
    thumbnail: "/images/youtube-pitch-thumb.jpg",
    summary: "Investor and partnership pitch deck with cinematic visual storytelling",
    intro: "A pitch deck that needed to close rooms \u2014 not just inform, but persuade with visual authority.",
    metadata: { year: 2025, duration: "2 Weeks", client: "YouTube (concept)", category: "Pitch Deck" },
    challenges: {
      heading: "Standard pitch decks rely on bullet points and charts. This needed to feel cinematic \u2014 more film pitch than startup deck.",
      body: "The audience was senior decision-makers with no patience for generic slides. Every frame needed to earn its place."
    },
    solutions: {
      heading: "We designed a narrative-driven deck with full-bleed visuals, minimal text, and a story arc that builds to the ask.",
      body: "The deck uses cinematic composition, data visualization with personality, and a clear narrative structure. It ships as both a presentation and a leave-behind PDF."
    },
    gallery: [
      "/images/youtube-pitch-thumb.jpg"
    ],
    externalLink: "https://www.canva.com/design/DAGiFpnFNE4/sg7LVWncTVPlmwoQRmg09g/view?utm_content=DAGiFpnFNE4&utm_campaign=designshare&utm_medium=link2&utm_source=uniquelinks&utlId=h9854372f9a"
  },
  // ── AI VIDEO PRODUCTION ──
  {
    slug: "comedy-mockumentary-teaser",
    title: "Comedy Mockumentary Teaser",
    client: "Internal",
    year: 2025,
    category: "Short Film",
    filterTag: "AI Video Production",
    thumbnailType: "video",
    thumbnail: "/videos/comedy-mockumentary-teaser.mp4",
    summary: "A comedy mockumentary teaser exploring the absurdity of being your own boss",
    intro: "A short-form comedy piece blending mockumentary style with AI-generated visuals.",
    metadata: { year: 2025, duration: "2 Weeks", client: "Internal", category: "Short Film" },
    challenges: {
      heading: "Creating authentic mockumentary tone with AI-generated footage required careful direction.",
      body: "The comedy needed to land naturally while using AI tools \u2014 balancing humor with visual quality."
    },
    solutions: {
      heading: "We combined AI video generation with sharp writing and precise editing to deliver genuine laughs.",
      body: "The result is a punchy teaser that proves AI-native content can carry comedic timing and tonal nuance."
    },
    gallery: [],
    videoPreviewUrl: "/videos/comedy-mockumentary-teaser.mp4",
    videoFullUrl: "/videos/comedy-mockumentary-teaser.mp4",
    isVideoLightbox: true
  },
  {
    slug: "on-spec-ad",
    title: "On Spec Ad",
    client: "Internal",
    year: 2025,
    category: "Ad Spec",
    filterTag: "AI Video Production",
    thumbnailType: "video",
    thumbnail: "/videos/on-spec-ad.mp4",
    summary: "A spec ad created entirely using AI tools \u2014 Runway Gen-4, Midjourney, and more",
    intro: "A spec commercial demonstrating the full power of AI-native ad production.",
    metadata: { year: 2025, duration: "1 Week", client: "Internal", category: "Ad Spec" },
    challenges: {
      heading: "Producing a broadcast-quality spec ad using only AI tools pushed every pipeline to its limits.",
      body: "The ad needed to look indistinguishable from traditional production while being made entirely with generative AI."
    },
    solutions: {
      heading: "We combined Runway Gen-4, Midjourney, and custom compositing to deliver a polished spec spot.",
      body: "The final piece demonstrates that AI-native production can match the quality bar of traditional ad filmmaking."
    },
    gallery: [],
    videoPreviewUrl: "/videos/on-spec-ad.mp4",
    videoFullUrl: "/videos/on-spec-ad.mp4",
    isVideoLightbox: true
  },
  {
    slug: "music-video-1",
    title: "F**k Them",
    client: "MAIA",
    year: 2025,
    category: "Music Video",
    filterTag: "AI Video Production",
    thumbnailType: "video",
    thumbnail: "/videos/music-video-1-full.mp4",
    summary: "AI-native music video with cinematic visual language",
    intro: "A music video that needed to feel like a short film \u2014 narrative-driven, visually dense, and completely original.",
    metadata: { year: 2025, duration: "5 Weeks", client: "MAIA", category: "Music Video" },
    challenges: {
      heading: "The artist wanted a visual world that didn't exist \u2014 surreal environments and impossible transitions that live-action alone couldn't deliver.",
      body: "Traditional VFX would have taken months and blown the budget. The creative vision demanded both speed and fidelity."
    },
    solutions: {
      heading: "We combined AI video generation with live-action performance footage, creating seamless transitions between real and surreal.",
      body: "Each scene was pre-visualized in AI, then shot and composited to match. The result plays like a high-budget production at a fraction of the cost and timeline."
    },
    gallery: [],
    videoPreviewUrl: "/videos/music-video-1-full.mp4",
    videoFullUrl: "/videos/music-video-1-full.mp4",
    isVideoLightbox: true
  },
  {
    slug: "music-video-2",
    title: "Hide It \u2014 Teaser",
    client: "Artist (TBA)",
    year: 2025,
    category: "Music Video",
    filterTag: "AI Video Production",
    thumbnailType: "video",
    thumbnail: "/videos/music-video-2-full.mp4",
    summary: "AI-native music video with cinematic visual language \u2014 Part II",
    intro: "The second installment in a visual series exploring AI-generated worlds blended with live performance.",
    metadata: { year: 2025, duration: "4 Weeks", client: "TBA", category: "Music Video" },
    challenges: {
      heading: "Maintaining visual continuity with Part I while pushing into new creative territory required a refined pipeline.",
      body: "The sequel needed to feel connected yet distinct \u2014 evolving the visual language without repeating it."
    },
    solutions: {
      heading: "We evolved the AI pipeline from Part I, introducing new generative techniques for environments and transitions.",
      body: "The result is a visual companion piece that stands alone while rewarding viewers who experience both parts together."
    },
    gallery: [],
    videoPreviewUrl: "/videos/music-video-2-preview.mp4",
    videoFullUrl: "/videos/music-video-2-full.mp4",
    isVideoLightbox: true
  },
  {
    slug: "animated-25-seconder",
    title: "Animated 25-Seconder",
    client: "Multi-client",
    year: 2025,
    category: "Animation",
    filterTag: "AI Video Production",
    thumbnailType: "video",
    thumbnail: "/videos/animated-25-seconder.mov",
    summary: "Short-form animated commercial spots for social and digital placement",
    intro: "Brands needed punchy, scroll-stopping 25-second spots optimized for Instagram, TikTok, and YouTube pre-roll.",
    metadata: { year: 2025, duration: "2 Weeks", client: "Multi-client", category: "Animation" },
    challenges: {
      heading: "Animated ads needed to hook in under 3 seconds, deliver a message in 30, and work without sound.",
      body: "Attention spans on social are brutal. The animations needed to be visually compelling enough to stop a thumb mid-scroll."
    },
    solutions: {
      heading: "We developed a rapid-production pipeline for animated spots \u2014 from concept to delivery in under two weeks.",
      body: "Each spot uses bold motion design, kinetic typography, and AI-assisted asset generation. Text overlays ensure the message lands with or without audio."
    },
    gallery: [
      "/images/animated-gallery.webp"
    ],
    videoPreviewUrl: "/videos/animated-25-seconder.mov",
    videoFullUrl: "/videos/animated-25-seconder.mov",
    isVideoLightbox: true
  }
];

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List The Anoma Company portfolio projects, optionally filtered by category (Solutions, Branding, Video Production, AI Video Production).",
  inputSchema: {
    filterTag: z.enum(["Solutions", "Branding", "Video Production", "AI Video Production"]).optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ filterTag }) => {
    const items = projects.filter((p) => !filterTag || p.filterTag === filterTag).map((p) => ({
      slug: p.slug,
      title: p.title,
      client: p.client,
      year: p.year,
      category: p.category,
      filterTag: p.filterTag,
      summary: p.summary,
      url: `https://theanoma.company/work/${p.slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, projects: items }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Get the full case-study details for one portfolio project by slug.",
  inputSchema: { slug: z2.string().trim().min(1).describe("Project slug, e.g. 'ai-chatbot'.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const project = projects.find((p) => p.slug === slug);
    if (!project) {
      return {
        content: [
          {
            type: "text",
            text: `No project with slug "${slug}". Use list_projects to see available slugs.`
          }
        ],
        isError: true
      };
    }
    const payload = { ...project, url: `https://theanoma.company/work/${project.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { project: payload }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";

// src/data/blogPosts.ts
var blogPosts = [
  {
    slug: "ai-reshaping-commercial-production",
    title: "How AI Is Reshaping Commercial Production",
    excerpt: "The tools have changed. The standards haven't. Here's how AI-native studios are delivering cinema-grade work at startup speed.",
    date: "Mar 2025",
    readTime: "6 min read",
    category: "Industry",
    thumbnail: "/images/filmmaking.webp",
    content: "AI is not replacing filmmakers \u2014 it's removing the barriers that kept great ideas from becoming great productions..."
  },
  {
    slug: "ctrl-ai-methodology",
    title: "The CTRL+AI Methodology: Our Creative Framework",
    excerpt: "Human control. AI execution. A structured approach to creative production that scales without losing soul.",
    date: "Feb 2025",
    readTime: "8 min read",
    category: "Process",
    thumbnail: "/images/bento-tech.webp",
    content: "Every project at The Anoma Company follows the same framework \u2014 CTRL+AI..."
  },
  {
    slug: "hybrid-workflows",
    title: "Hybrid Workflows: When to Shoot, When to Generate",
    excerpt: "Not everything should be AI-generated. Not everything needs a camera. The art is knowing which tool fits which moment.",
    date: "Jan 2025",
    readTime: "5 min read",
    category: "Workflow",
    thumbnail: "/images/mosaic-production.webp",
    content: "The best productions in 2025 aren't purely AI or purely traditional \u2014 they're hybrid..."
  },
  {
    slug: "building-ai-first-studio",
    title: "Building an AI-First Studio from Scratch",
    excerpt: "What it took to build a creative studio where AI isn't a feature \u2014 it's the foundation.",
    date: "Dec 2024",
    readTime: "7 min read",
    category: "Behind the Scenes",
    thumbnail: "/images/blog-ai-studio.webp",
    content: "When we started The Anoma Company, the question wasn't whether to use AI \u2014 it was how to build everything around it..."
  }
];

// src/lib/mcp/tools/list-blog-posts.ts
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List The Anoma Company journal/blog posts with titles, excerpts and slugs.",
  inputSchema: {
    category: z3.string().trim().min(1).optional().describe("Optional category filter, e.g. 'Process'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = blogPosts.filter((p) => !category || p.category.toLowerCase() === category.toLowerCase()).map(({ slug, title, excerpt, date, readTime, category: cat }) => ({
      slug,
      title,
      excerpt,
      date,
      readTime,
      category: cat,
      url: `https://theanoma.company/blog/${slug}`
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, posts: items }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool4({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Get the full content of one journal/blog post by slug.",
  inputSchema: { slug: z4.string().trim().min(1).describe("Blog post slug.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const post = blogPosts.find((p) => p.slug === slug);
    if (!post) {
      return {
        content: [{ type: "text", text: `No blog post with slug "${slug}".` }],
        isError: true
      };
    }
    const payload = { ...post, url: `https://theanoma.company/blog/${post.slug}` };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: { post: payload }
    };
  }
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/data/faqs.ts
var faqs = [
  {
    question: "What does 'AI-first' actually mean?",
    answer: "It means AI is the foundation of our creative pipeline \u2014 not an afterthought. From concept to delivery, AI tools drive speed, consistency, and scale. Human creative direction steers every project."
  },
  {
    question: "Can AI-generated content match traditional production quality?",
    answer: "Yes. Our AI-generated visuals are cinema-grade. We've been featured on PhotoVogue Italia and deliver assets that hold up on billboards, broadcast, and film screens."
  },
  {
    question: "Are there copyright issues with AI content?",
    answer: "No. All content we produce is fully licensed for commercial use. We structure every project to ensure clean IP and zero copyright concerns."
  },
  {
    question: "What's your typical turnaround time?",
    answer: "Most projects ship in 2\u20134 weeks depending on scope. Our AI pipeline lets us move 3\u20135x faster than traditional production without sacrificing quality."
  },
  {
    question: "Do you work with agencies or only direct clients?",
    answer: "Both. We partner with agencies as a white-label production arm and work directly with brands. Either way, the process is the same."
  },
  {
    question: "Can you match our existing brand guidelines?",
    answer: "Absolutely. We integrate with your brand system \u2014 fonts, colors, tone, visual language \u2014 and extend it through AI-generated assets that feel native to your brand."
  },
  {
    question: "What's the CTRL+AI methodology?",
    answer: "It's our proprietary framework: human Control + AI execution. Every project follows structured phases \u2014 Discovery, Direction, Production, Delivery \u2014 with human checkpoints at each stage."
  }
];

// src/lib/mcp/tools/list-faqs.ts
var list_faqs_default = defineTool5({
  name: "list_faqs",
  title: "List FAQs",
  description: "List The Anoma Company frequently asked questions and their answers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(faqs, null, 2) }],
    structuredContent: { count: faqs.length, faqs }
  })
});

// src/lib/mcp/tools/get-studio-info.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/data/siteConfig.ts
var siteConfig = {
  name: "The Anoma Company",
  tagline: "Everything else is noise.",
  description: "AI-First Creative Studio. Campaigns, tools, and brand systems.",
  email: "admin@theanoma.company",
  phone: "+1 (647) 564-8106",
  phoneAlt: "+91 81698 63268",
  address: "Toronto, ON, Canada",
  socials: {
    instagram: "https://www.instagram.com/theanomacompany/",
    linkedin: "https://www.linkedin.com/company/the-anoma-company",
    youtube: "https://www.youtube.com/@CTRLplusAI/",
    twitter: ""
  },
  showreelYoutubeId: "XlaBgDLMuGQ"
};

// src/data/team.ts
var team = [
  {
    name: "Dr. Uday K Ghosh",
    role: "Chairman Emeritus",
    image: "/images/uday-ghosh.jpg",
    linkedin: "https://www.linkedin.com/in/udoayghosh/"
  },
  {
    name: "Surzayon",
    role: "Founder & Creative Director",
    image: "/images/surzayon.png",
    linkedin: "https://www.linkedin.com/in/surzayon/"
  },
  {
    name: "Sreejeeta",
    role: "Co-Founder, Head of Strategy and Creative Development",
    image: "/images/sreejeeta.jpg",
    linkedin: "https://www.linkedin.com/in/sreejeeta-ghosh/"
  },
  {
    name: "Diana",
    role: "Head of Internal Operations",
    image: "/images/diana.png"
  },
  {
    name: "Aeria",
    role: "AI Influencer",
    image: "/images/aeria-portrait.png",
    isAI: true
  }
];

// src/data/stats.ts
var stats = [
  { value: 29, suffix: "+", label: "Projects Delivered" },
  { value: 6, suffix: "+", label: "AI Tools Built" },
  { value: 3, suffix: "", label: "Countries" }
];

// src/lib/mcp/tools/get-studio-info.ts
var get_studio_info_default = defineTool6({
  name: "get_studio_info",
  title: "Get studio info",
  description: "Get The Anoma Company studio overview: positioning, contact details, social links, team and headline stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = { site: siteConfig, team, stats, website: "https://theanoma.company" };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/submit-inquiry.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/submit-inquiry.ts
var submit_inquiry_default = defineTool7({
  name: "submit_inquiry",
  title: "Submit inquiry",
  description: "Send a new project inquiry to The Anoma Company. Creates a contact submission the studio team will follow up on.",
  inputSchema: {
    name: z5.string().trim().min(1).max(100).describe("Contact name."),
    email: z5.string().trim().email().max(255).describe("Contact email address."),
    message: z5.string().trim().min(1).max(2e3).describe("What the project is about."),
    company: z5.string().trim().max(150).optional(),
    phone: z5.string().trim().max(40).optional(),
    service_interest: z5.string().trim().max(120).optional().describe("Service of interest, e.g. 'AI Video Production'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("contact_submissions").insert({
      name: input.name,
      email: input.email,
      message: input.message,
      company: input.company ?? null,
      phone: input.phone ?? null,
      service_interest: input.service_interest ?? null
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Inquiry submitted. The studio will be in touch shortly." }],
      structuredContent: { submitted: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zognntitkkavfvwxbjld";
var mcp_default = defineMcp({
  name: "theanomacompany",
  title: "theanomacompany",
  version: "0.1.0",
  instructions: "Tools for The Anoma Company, an AI-first creative studio. Browse portfolio case studies, journal articles, FAQs and studio info, and submit a project inquiry on behalf of the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_projects_default,
    get_project_default,
    list_blog_posts_default,
    get_blog_post_default,
    list_faqs_default,
    get_studio_info_default,
    submit_inquiry_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
